-- Deprecated reference file.
--
-- Database schema changes are now managed through Supabase CLI migrations.
-- Do not run this file during deployment.
--
-- Current initial schema:
-- supabase/migrations/20260814202055_initial_schema.sql
